spring:
  application:
    name: UserApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_tracking
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: user-group

server:
  port: 8081

#logging:
#  level:
#    org.springframework.web: "debug"
#    org.hibernate: "error"
#logging.level.org.springframework.security: DEBUG